// cli/templates/react-papi/src/components/Avatar.tsx
import { useProfile } from '../hooks/useProfile'

interface AvatarProps {
  name?: string
  address?: string
  status?: 'online' | 'none'
}

export default function Avatar({ name, address, status = 'none' }: AvatarProps) {
  const { displayName, displayAddress, getInitials } = useProfile({ name, address })

  const avatarClasses = [
    'avatar',
    'avatar-placeholder',
    status === 'online' ? 'avatar-online' : '',
  ].join(' ')

  return (
    <div className="flex items-center gap-3">
      <div className={avatarClasses}>
        <div className="w-8 bg-neutral text-neutral-content rounded-full">
          <span className="text-xs flex items-center justify-center h-full">
            {getInitials(displayName || displayAddress)}
          </span>
        </div>
      </div>
      <div>
        {displayName ? <div className="text-xs text-black font-medium">{displayName}</div> : null}
        {displayAddress ? <div className="text-xs text-gray-400">{displayAddress}</div> : null}
      </div>
    </div>
  )
}

// cli/templates/vue-papi/src/components/Avatar.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useProfile } from '../composables/useProfile'

interface Props {
  name?: string
  address?: string
  status?: 'online' | 'none'
}

const props = withDefaults(defineProps<Props>(), {
  status: 'none',
})

const { displayName, displayAddress, getInitials } = useProfile(props)

const avatarClasses = computed(() => {
  const classes = ['avatar', 'avatar-placeholder']

  if (props.status === 'online')
    classes.push('avatar-online')

  return classes.join(' ')
})
</script>

<template>
  <div class="flex items-center gap-3">
    <div :class="avatarClasses">
      <div class="w-8 bg-neutral text-neutral-content rounded-full">
        <span class="text-xs flex items-center justify-center h-full">
          {{ getInitials(displayName || displayAddress) }}
        </span>
      </div>
    </div>
    <div>
      <div v-if="displayName" class="text-xs text-black font-medium">
        {{ displayName }}
      </div>
      <div v-if="displayAddress" class="text-xs text-gray-400">
        {{ displayAddress }}
      </div>
    </div>
  </div>
</template>
