// templates/solidity-hardhat-wagmi/dapp-vue/src/components/Header.vue
<script setup lang="ts">
import Connect from './Connect.vue'
</script>

<template>
  <div class="navbar bg-base-100 border-b border-gray-200">
    <div class="container mx-auto px-4 flex items-center">
      <div class="navbar-start">
        <a href="https://polkadot.com" target="_blank" class="flex items-center">
          <span class="icon-[token-branded--polkadot] text-2xl" />
          <span class="text-xl font-bold font-mono text-black tracking-wide ml-1">
            Dapp
          </span>
        </a>
      </div>
      <div class="navbar-end">
        <Connect />
      </div>
    </div>
  </div>
</template>

// templates/ink-v6/react-papi/src/components/Header.tsx
import Connect from './Connect'

export default function Header() {
  return (
    <div className="navbar bg-base-100 border-b border-gray-200">
      <div className="container mx-auto flex items-center">
        <div className="navbar-start">
          <a href="https://polkadot.com" target="_blank" className="flex items-center" rel="noopener noreferrer">
            <span className="icon-[token-branded--polkadot] text-2xl" />
            <span className="text-xl font-bold font-mono text-black tracking-wide ml-1">
              Dapp
            </span>
          </a>
        </div>
        <div className="navbar-end">
          <Connect />
        </div>
      </div>
    </div>
  )
}
