// templates/ink-v6/react-dedot/src/components/ContractData.tsx
import type { Prefix } from '~/utils/sdk'
import { useEffect } from 'react'
import { useContractQuery } from '~/hooks/useContractQuery'

interface ContractDataProps {
  chainKey: Prefix
  address?: string
}

export default function ContractData({ chainKey, address }: ContractDataProps) {
  const { contractValue, isLoading, error, queryContractValue } = useContractQuery(chainKey, address)

  useEffect(() => {
    if (address) {
      queryContractValue()
    }
  }, [address, queryContractValue])

  return (
    <div>
      <div className="flex items-center justify-between mb-3">
        <div className="text-xs text-gray-500 uppercase tracking-wider">
          Contract Value
        </div>
        {address
          ? (
              <button
                type="button"
                className="btn btn-xs btn-ghost"
                disabled={isLoading}
                onClick={queryContractValue}
              >
                {isLoading
                  ? (
                      <span className="icon-[mdi--loading] animate-spin" />
                    )
                  : (
                      <span className="icon-[mdi--refresh]" />
                    )}
              </button>
            )
          : null}
      </div>

      {isLoading && contractValue === null
        ? (
            <div className="flex items-center gap-3 h-12">
              <span className="icon-[mdi--loading] animate-spin text-3xl text-gray-400" />
              <span className="font-mono font-light text-gray-400 text-xl">Loading...</span>
            </div>
          )
        : error
          ? (
              <div className="text-sm text-red-600 py-2">
                {error}
              </div>
            )
          : contractValue !== null
            ? (
                <div>
                  <div className="flex items-center gap-3 h-12">
                    {contractValue
                      ? (
                          <span className="icon-[mdi--toggle-switch] text-green-600 text-3xl" />
                        )
                      : (
                          <span className="icon-[mdi--toggle-switch-off] text-gray-400 text-3xl" />
                        )}
                    <span className="font-mono font-light text-black text-xl">{contractValue ? 'TRUE' : 'FALSE'}</span>
                  </div>
                </div>
              )
            : (
                <div className="text-sm text-gray-400 py-2">
                  No data
                </div>
              )}
    </div>
  )
}

// templates/ink-v6/dapp-vue-dedot/src/components/ContractData.vue
<script setup lang="ts">
import type { Prefix } from '~/utils/sdk'
import { onMounted } from 'vue'
import { useContractQuery } from '~/composables/useContractQuery'

const props = defineProps<{
  chainKey: Prefix
  address?: string
}>()

const { contractValue, isLoading, error, queryContractValue } = useContractQuery(props.chainKey, props.address)

onMounted(() => {
  if (props.address) {
    queryContractValue()
  }
})
</script>

<template>
  <div>
    <div class="flex items-center justify-between mb-3">
      <div class="text-xs text-gray-500 uppercase tracking-wider">
        Contract Value
      </div>
      <button
        v-if="address"
        class="btn btn-xs btn-ghost"
        :disabled="isLoading"
        @click="queryContractValue"
      >
        <span v-if="isLoading" class="icon-[mdi--loading] animate-spin" />
        <span v-else class="icon-[mdi--refresh]" />
      </button>
    </div>

    <div v-if="isLoading && contractValue === null" class="flex items-center gap-3 h-12">
      <span class="icon-[mdi--loading] animate-spin text-3xl text-gray-400" />
      <span class="font-mono font-light text-gray-400 text-xl">Loading...</span>
    </div>

    <div v-else-if="error" class="text-sm text-red-600 py-2">
      {{ error }}
    </div>

    <div v-else-if="contractValue !== null">
      <div class="flex items-center gap-3 h-12">
        <span v-if="contractValue" class="icon-[mdi--toggle-switch] text-green-600 text-3xl" />
        <span v-else class="icon-[mdi--toggle-switch-off] text-gray-400 text-3xl" />
        <span class="font-mono font-light text-black text-xl">{{ contractValue ? 'TRUE' : 'FALSE' }}</span>
      </div>
    </div>

    <div v-else class="text-sm text-gray-400 py-2">
      No data
    </div>
  </div>
</template>
