// templates/react-papi/src/components/Connect.tsx
import { useRef, useState } from 'react'
import { useConnect } from '~/hooks/useConnect'
import Avatar from './Avatar'

export default function Connect() {
  const connectModal = useRef<HTMLDialogElement | null>(null)
  const [showOtherWallets, setShowOtherWallets] = useState(false)

  const {
    listAccounts,
    selectedAccount,
    connectedWallet,
    isConnecting,
    installedWallets,
    availableWallets,
    connect,
    disconnect,
    selectAccount,
  } = useConnect()

  function handleSelectAccount(account: any) {
    if (account) {
      selectAccount(account)
      connectModal.current?.close()
    }
  }

  function openConnectModal() {
    connectModal.current?.showModal()
  }

  function closeConnectModal() {
    connectModal.current?.close()
  }

  function toggleOtherWallets() {
    setShowOtherWallets(!showOtherWallets)
  }

  function isWalletConnected(wallet: any) {
    return connectedWallet?.extensionName === wallet?.extensionName
  }

  function isAccountSelected(account: any) {
    return selectedAccount?.address === account?.address
  }

  return (
    <div>
      {/* Connect Button */}
      {!selectedAccount
        ? (
            <button
              type="button"
              className="btn btn-neutral btn-sm uppercase tracking-wider"
              onClick={openConnectModal}
            >
              Connect Wallet
            </button>
          )
        : (
            // Connected Account Display
            <div className="flex items-center justify-between gap-2">
              <div className="hidden sm:block">
                <Avatar
                  name={selectedAccount.name}
                  address={selectedAccount.address}
                  status="online"
                />
              </div>
              <div className="flex gap-2">
                <button
                  type="button"
                  className="btn btn-outline btn-sm uppercase tracking-wider hidden sm:block"
                  onClick={openConnectModal}
                >
                  Change
                </button>
                <button
                  type="button"
                  className="btn btn-outline btn-sm uppercase tracking-wider"
                  onClick={disconnect}
                >
                  Disconnect
                </button>
              </div>
            </div>
          )}

      {/* Modal using HTML dialog element */}
      <dialog ref={connectModal} className="modal modal-bottom sm:modal-middle">
        <div className="modal-box max-w-2xl">
          {/* Header */}
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-lg font-medium text-black uppercase tracking-wider">
              CONNECT WALLET
            </h2>
            <button type="button" className="btn btn-sm btn-circle btn-ghost" onClick={closeConnectModal}>
              <span className="icon-[mdi--close]" />
            </button>
          </div>

          {/* Account Selection */}
          {listAccounts.length > 0 && (
            <div className="mb-6">
              <h3 className="text-xs text-gray-500 uppercase tracking-wider mb-3">
                Select Account
              </h3>
              <div className="space-y-2">
                {listAccounts.map(account => (
                  <div
                    key={account.address}
                    className={`card card-compact bg-base-100 border cursor-pointer hover:shadow-md transition-shadow ${
                      isAccountSelected(account)
                        ? 'border-primary'
                        : 'border-base-300 hover:border-primary'
                    }`}
                    onClick={() => handleSelectAccount(account)}
                  >
                    <div className="card-body">
                      <div className="flex items-center justify-between">
                        <Avatar name={account.name} address={account.address} />
                        {isAccountSelected(account) && (
                          <div className="w-2 h-2 bg-primary rounded-full" />
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Installed */}
          {installedWallets.length > 0 && (
            <div className="mb-6">
              <h3 className="text-xs text-gray-500 uppercase tracking-wider mb-3">
                Installed
              </h3>
              <div className="grid grid-cols-2 lg:grid-cols-3 gap-3">
                {installedWallets.map(wallet => (
                  <div
                    key={wallet.installUrl}
                    className={`card card-compact bg-base-100 border cursor-pointer hover:shadow-md transition-shadow ${
                      isWalletConnected(wallet)
                        ? 'border-success'
                        : 'border-base-300 hover:border-primary'
                    }`}
                    onClick={() => connect(wallet)}
                  >
                    <div className="card-body items-center text-center">
                      <div className="relative">
                        <img
                          src={wallet.logo.src}
                          alt={wallet.logo.alt}
                          className="w-12 h-12"
                        />
                        {isWalletConnected(wallet) && (
                          <div className="absolute -top-1 -right-1 w-4 h-4 bg-success rounded-full flex items-center justify-center">
                            <span className="icon-[mdi--check] w-2 h-2 text-white" />
                          </div>
                        )}
                      </div>
                      <div className="text-xs font-medium text-black">
                        {wallet.title}
                      </div>
                      <button
                        type="button"
                        disabled={isConnecting === wallet.extensionName}
                        className="btn btn-neutral btn-sm w-32 uppercase tracking-wider"
                      >
                        {isConnecting === wallet.extensionName && (
                          <span className="icon-[mdi--loading] animate-spin" />
                        )}
                        {isWalletConnected(wallet)
                          ? (
                              'Connected'
                            )
                          : isConnecting === wallet.extensionName
                            ? (
                                'Connecting'
                              )
                            : (
                                'Connect'
                              )}
                        {!isWalletConnected(wallet) && (
                          <span className="icon-[mdi--chevron-right]" />
                        )}
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Other Wallets */}
          {availableWallets.length > 0 && (
            <div>
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-xs text-gray-500 uppercase tracking-wider">
                  Other wallets
                </h3>
                <button type="button" className="btn btn-ghost btn-sm" onClick={toggleOtherWallets}>
                  {showOtherWallets ? 'Hide' : 'Show'}
                  <span
                    className={showOtherWallets ? 'icon-[mdi--chevron-up]' : 'icon-[mdi--chevron-down]'}
                  />
                </button>
              </div>
              {showOtherWallets && (
                <div className="grid grid-cols-2 lg:grid-cols-3 gap-3">
                  {availableWallets.map(wallet => (
                    <div
                      key={wallet.installUrl}
                      className="card card-compact bg-base-100 border border-base-300 hover:border-primary hover:shadow-md transition-all"
                    >
                      <div className="card-body items-center text-center">
                        <img
                          src={wallet.logo.src}
                          alt={wallet.logo.alt}
                          className="w-12 h-12 opacity-60"
                        />
                        <div className="text-xs font-medium text-black">
                          {wallet.title}
                        </div>
                        <a
                          href={wallet.installUrl}
                          target="_blank"
                          className="btn btn-neutral btn-sm w-32 uppercase tracking-wider"
                        >
                          <span>Download</span>
                          <span className="icon-[mdi--download]" />
                        </a>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
        <form method="dialog" className="modal-backdrop">
          <button type="button">close</button>
        </form>
      </dialog>
    </div>
  )
}

// cli/templates/vue-dedot/src/components/Connect.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useConnect } from '~/composables/useConnect'
import Avatar from './Avatar.vue'

const connectModal = ref<HTMLDialogElement | null>(null)
const showOtherWallets = ref(false)

const {
  listAccounts,
  selectedAccount,
  connectedWallet,
  isConnecting,
  installedWallets,
  availableWallets,
  connect,
  disconnect,
  selectAccount,
} = useConnect()

function handleSelectAccount(account: typeof selectedAccount.value) {
  if (account) {
    selectAccount(account)
    connectModal.value?.close()
  }
}

function openConnectModal() {
  connectModal.value?.showModal()
}

function closeConnectModal() {
  connectModal.value?.close()
}

function toggleOtherWallets() {
  showOtherWallets.value = !showOtherWallets.value
}

function isWalletConnected(wallet: typeof connectedWallet.value) {
  return connectedWallet.value?.extensionName === wallet?.extensionName
}

function isAccountSelected(account: typeof selectedAccount.value) {
  return selectedAccount.value?.address === account?.address
}
</script>

<template>
  <div>
    <!-- Connect Button -->
    <div v-if="!selectedAccount">
      <button
        class="btn btn-neutral btn-sm uppercase tracking-wider"
        @click="openConnectModal"
      >
        Connect Wallet
      </button>
    </div>

    <!-- Connected Account Display -->
    <div v-else>
      <div class="flex items-center justify-between gap-2">
        <Avatar
          :name="selectedAccount.name"
          :address="selectedAccount.address"
          status="online"
          class="hidden sm:block"
        />
        <div class="flex gap-2">
          <button
            class="btn btn-outline btn-sm uppercase tracking-wider hidden sm:block"
            @click="openConnectModal"
          >
            Change
          </button>
          <button
            class="btn btn-outline btn-sm uppercase tracking-wider"
            @click="disconnect"
          >
            Disconnect
          </button>
        </div>
      </div>
    </div>

    <!-- Modal using HTML dialog element -->
    <dialog ref="connectModal" class="modal modal-bottom sm:modal-middle">
      <div class="modal-box max-w-2xl">
        <!-- Header -->
        <div class="flex items-center justify-between mb-6">
          <h2 class="text-lg font-medium text-black uppercase tracking-wider">
            CONNECT WALLET
          </h2>
          <button class="btn btn-sm btn-circle btn-ghost" @click="closeConnectModal">
            <span class="icon-[mdi--close]" />
          </button>
        </div>

        <!-- Account Selection -->
        <div v-if="listAccounts.length" class="mb-6">
          <h3 class="text-xs text-gray-500 uppercase tracking-wider mb-3">
            Select Account
          </h3>
          <div class="space-y-2">
            <div
              v-for="account in listAccounts"
              :key="account.address"
              class="card card-compact bg-base-100 border cursor-pointer hover:shadow-md transition-shadow"
              :class="isAccountSelected(account) ? 'border-primary' : 'border-base-300 hover:border-primary'"
              @click="handleSelectAccount(account)"
            >
              <div class="card-body">
                <div class="flex items-center justify-between">
                  <Avatar
                    :name="account.name"
                    :address="account.address"
                  />
                  <div v-if="isAccountSelected(account)">
                    <div class="w-2 h-2 bg-primary rounded-full" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Installed -->
        <div v-if="installedWallets.length" class="mb-6">
          <h3 class="text-xs text-gray-500 uppercase tracking-wider mb-3">
            Installed
          </h3>
          <div class="grid grid-cols-2 lg:grid-cols-4 gap-3">
            <div
              v-for="wallet in installedWallets"
              :key="wallet.extensionName"
              class="card card-compact bg-base-100 border cursor-pointer hover:shadow-md transition-shadow"
              :class="isWalletConnected(wallet) ? 'border-success' : 'border-base-300 hover:border-primary'"
              @click="connect(wallet)"
            >
              <div class="card-body items-center text-center">
                <div class="relative">
                  <img
                    :src="wallet.logo.src"
                    :alt="wallet.logo.alt"
                    class="w-12 h-12"
                  >
                  <div v-if="isWalletConnected(wallet)" class="absolute -top-1 -right-1 w-4 h-4 bg-success rounded-full flex items-center justify-center">
                    <span class="icon-[mdi--check] w-2 h-2 text-white" />
                  </div>
                </div>
                <div class="text-xs font-medium text-black">
                  {{ wallet.title }}
                </div>
                <button
                  :disabled="isConnecting === wallet.extensionName"
                  class="btn btn-neutral btn-sm w-32 uppercase tracking-wider"
                >
                  <span v-if="isConnecting === wallet.extensionName" class="icon-[mdi--loading] animate-spin" />
                  <span v-if="isWalletConnected(wallet)">Connected</span>
                  <span v-else>{{ isConnecting === wallet.extensionName ? 'Connecting' : 'Connect' }}</span>
                  <span v-if="!isWalletConnected(wallet)" class="icon-[mdi--chevron-right]" />
                </button>
              </div>
            </div>
          </div>
        </div>

        <!-- Other Wallets -->
        <div v-if="availableWallets.length">
          <div class="flex items-center justify-between mb-3">
            <h3 class="text-xs text-gray-500 uppercase tracking-wider">
              Other wallets
            </h3>
            <button class="btn btn-ghost btn-sm" @click="toggleOtherWallets">
              {{ showOtherWallets ? 'Hide' : 'Show' }}
              <span :class="showOtherWallets ? 'icon-[mdi--chevron-up]' : 'icon-[mdi--chevron-down]'" />
            </button>
          </div>
          <div v-if="showOtherWallets" class="grid grid-cols-2 lg:grid-cols-4 gap-3">
            <div
              v-for="wallet in availableWallets"
              :key="wallet.extensionName"
              class="card card-compact bg-base-100 border border-base-300 hover:border-primary hover:shadow-md transition-all"
            >
              <div class="card-body items-center text-center">
                <img
                  :src="wallet.logo.src"
                  :alt="wallet.logo.alt"
                  class="w-12 h-12 opacity-60"
                >
                <div class="text-xs font-medium text-black">
                  {{ wallet.title }}
                </div>
                <a
                  :href="wallet.installUrl"
                  target="_blank"
                  class="btn btn-neutral btn-sm w-32 uppercase tracking-wider"
                >
                  <span>Download</span>
                  <span class="icon-[mdi--download]" />
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <form method="dialog" class="modal-backdrop">
        <button>close</button>
      </form>
    </dialog>
  </div>
</template>
