// templates/solidity-hardhat-wagmi/dapp-vue/src/components/Connect.vue
<script setup lang="ts">
import type { Connector } from '@wagmi/vue'
import type { Chain } from '@wagmi/vue/chains'
import { useAccount, useChainId, useChains, useConnect, useConnectorClient, useDisconnect } from '@wagmi/vue'
import { computed, ref } from 'vue'
import { ensurePaseoTestnet } from '../utils/chain'
import { shortenAddress } from '../utils/formatters'

// Popular wallets for when no connectors are available
const popularWallets = [
  {
    id: 'metamask',
    name: 'MetaMask',
    downloadUrl: 'https://metamask.io/download/',
  },
  {
    id: 'talisman',
    name: 'Talisman Wallet',
    downloadUrl: 'https://talisman.xyz/',
  },
]

const connectModal = ref<HTMLDialogElement | null>(null)
const chainId = useChainId()
const chains = useChains()
const { connect, connectors, error, status } = useConnect()
const { disconnect } = useDisconnect()
const { address, isConnected, connector } = useAccount()
const { data: connectorClient } = useConnectorClient()

// Get the connected chain instead of using config
const connectedChain = computed(() => {
  return chains.value.find((chain: Chain) => chain.id === chainId.value) || chains.value[0]
})

// Filter connectors to show only MetaMask and Talisman
const filteredConnectors = computed(() => {
  return connectors.filter((connector) => {
    const id = connector.id.toLowerCase()
    return id.includes('metamask') || id.includes('talisman')
  })
})

function openConnectModal() {
  connectModal.value?.showModal()
}

function closeConnectModal() {
  connectModal.value?.close()
}

async function handleConnect(connector: Connector) {
  try {
    // Connect first to get the client
    connect({ connector, chainId: connectedChain.value.id })
    closeConnectModal()

    // Add chain after connection if client is available
    if (connectorClient.value) {
      try {
        await ensurePaseoTestnet(connectorClient.value)
      }
      catch (err) {
        console.error('Failed to add chain:', err)
      }
    }
  }
  catch (err) {
    console.error('Failed to connect:', err)
    closeConnectModal()
  }
}

function handleDisconnect() {
  disconnect()
  localStorage.clear()
}
</script>

<template>
  <!-- Connect/Disconnect Buttons -->
  <div class="flex items-center gap-2">
    <button
      class="btn btn-outline btn-sm font-mono"
      @click="openConnectModal"
    >
      <div v-if="!isConnected" class="flex items-center gap-2">
        <span class="icon-[mdi--wallet] w-4 h-4" />
        <span>Connect Wallet</span>
      </div>
      <div v-else class="flex items-center gap-2">
        <img
          v-if="connector?.icon"
          :src="connector.icon"
          :alt="connector.name"
          class="w-4 h-4"
        >
        <span v-else class="icon-[mdi--wallet] w-4 h-4" />
        <span class="hidden sm:block">{{ address ? shortenAddress(address) : '' }}</span>
      </div>
    </button>

    <!-- Disconnect Button (only shown when connected) -->
    <button
      v-if="isConnected"
      class="btn btn-outline btn-sm font-mono"
      @click="handleDisconnect"
    >
      <span class="icon-[mdi--logout] w-4 h-4" />
    </button>
  </div>

  <!-- Modal -->
  <dialog ref="connectModal" class="modal modal-bottom sm:modal-middle">
    <div class="modal-box max-w-md">
      <!-- Header -->
      <div class="flex items-center justify-between mb-6">
        <div>
          <h2 class="text-lg font-medium text-black uppercase tracking-wider">
            CONNECT WALLET
          </h2>
          <p class="text-xs text-gray-500 mt-1">
            Network: {{ connectedChain.name }}
          </p>
        </div>
        <button class="btn btn-sm btn-circle btn-ghost" @click="closeConnectModal">
          <span class="icon-[mdi--close] w-4 h-4" />
        </button>
      </div>

      <!-- Available Connectors -->
      <div v-if="filteredConnectors.length" class="mb-6">
        <h3 class="text-xs text-gray-500 uppercase tracking-wider mb-3">
          Available Wallets
        </h3>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-3">
          <div
            v-for="conn in filteredConnectors"
            :key="conn.id"
            class="card card-compact bg-base-100 border border-base-300 hover:border-primary hover:shadow-md transition-all cursor-pointer"
            @click="handleConnect(conn)"
          >
            <div class="card-body items-center text-center">
              <div class="flex items-center justify-center w-12 h-12 mb-2">
                <img
                  v-if="conn.icon"
                  :src="conn.icon"
                  :alt="conn.name"
                  class="w-8 h-8"
                >
                <span v-else class="icon-[mdi--wallet-outline] w-8 h-8" />
              </div>
              <div class="text-sm font-medium text-black">
                {{ conn.name }}
              </div>
              <button
                :disabled="status === 'pending'"
                class="btn btn-neutral btn-sm w-32 uppercase tracking-wider mt-2"
              >
                <span v-if="status === 'pending'" class="icon-[mdi--loading] animate-spin" />
                <span v-if="status === 'pending'">Connecting</span>
                <span v-else>Connect</span>
                <span v-if="status !== 'pending'" class="icon-[mdi--chevron-right]" />
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- No Connectors Available - Show Popular Wallets -->
      <div v-else class="space-y-3">
        <div class="text-center mb-4">
          <div class="icon-[mdi--wallet-outline] w-16 h-16 mx-auto text-gray-300 mb-2" />
          <p class="text-sm text-gray-500">
            No wallet extensions detected
          </p>
          <p class="text-xs text-gray-400">
            Download a wallet to get started
          </p>
        </div>

        <h3 class="text-xs text-gray-500 uppercase tracking-wider mb-3">
          Popular Wallets
        </h3>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-3">
          <div
            v-for="wallet in popularWallets"
            :key="wallet.id"
            class="card card-compact bg-base-100 border border-base-300 hover:border-primary hover:shadow-md transition-all"
          >
            <div class="card-body items-center text-center">
              <div class="text-sm font-medium text-black mb-3">
                {{ wallet.name }}
              </div>
              <a
                :href="wallet.downloadUrl"
                target="_blank"
                class="btn btn-neutral btn-sm w-32 uppercase tracking-wider"
              >
                <span>Download</span>
                <span class="icon-[mdi--download] w-4 h-4" />
              </a>
            </div>
          </div>
        </div>
      </div>

      <!-- Error Display -->
      <div v-if="error" class="alert alert-error mt-4">
        <span>{{ error.message }}</span>
      </div>
    </div>
    <form method="dialog" class="modal-backdrop">
      <button>close</button>
    </form>
  </dialog>
</template>

// templates/solidity-hardhat-wagmi/dapp-react/src/components/Connect.tsx
import type { Chain } from 'wagmi/chains'
import { useMemo, useRef } from 'react'
import { useAccount, useChainId, useChains, useConnect, useConnectorClient, useDisconnect } from 'wagmi'
import { ensurePaseoTestnet } from '../utils/chain'
import { shortenAddress } from '../utils/formatters'

// Popular wallets for when no connectors are available
const popularWallets = [
  {
    id: 'metamask',
    name: 'MetaMask',
    downloadUrl: 'https://metamask.io/download/',
  },
  {
    id: 'talisman',
    name: 'Talisman Wallet',
    downloadUrl: 'https://talisman.xyz/',
  },
]

export default function Connect() {
  const connectModalRef = useRef<HTMLDialogElement>(null)
  const chainId = useChainId()
  const chains = useChains()
  const { connect, connectors, error, status } = useConnect()
  const { disconnect } = useDisconnect()
  const { address, isConnected, connector } = useAccount()
  const { data: connectorClient } = useConnectorClient()

  // Get the connected chain instead of using config
  const connectedChain = useMemo(() => {
    return chains.find((chain: Chain) => chain.id === chainId) || chains[0]
  }, [chains, chainId])

  // Filter connectors to show only MetaMask and Talisman
  const filteredConnectors = useMemo(() => {
    return connectors.filter((connector) => {
      const id = connector.id.toLowerCase()
      return id.includes('metamask') || id.includes('talisman')
    })
  }, [connectors])

  function openConnectModal() {
    connectModalRef.current?.showModal()
  }

  function closeConnectModal() {
    connectModalRef.current?.close()
  }

  async function handleConnect(connector: any) {
    try {
      // Connect first to get the client
      connect({ connector, chainId: connectedChain.id as any })
      closeConnectModal()

      // Add chain after connection if client is available
      if (connectorClient) {
        try {
          await ensurePaseoTestnet(connectorClient)
        }
        catch (err) {
          console.error('Failed to add chain:', err)
        }
      }
    }
    catch (err) {
      console.error('Failed to connect:', err)
      closeConnectModal()
    }
  }

  function handleDisconnect() {
    disconnect()
    localStorage.clear()
  }

  return (
    <>
      {/* Connect/Disconnect Buttons */}
      <div className="flex items-center gap-2">
        <button
          type="button"
          className="btn btn-outline btn-sm font-mono"
          onClick={openConnectModal}
        >
          {!isConnected
            ? (
                <div className="flex items-center gap-2">
                  <span className="icon-[mdi--wallet] w-4 h-4" />
                  <span>Connect Wallet</span>
                </div>
              )
            : (
                <div className="flex items-center gap-2">
                  {connector?.icon
                    ? (
                        <img
                          src={connector.icon}
                          alt={connector.name}
                          className="w-4 h-4"
                        />
                      )
                    : (
                        <span className="icon-[mdi--wallet] w-4 h-4" />
                      )}
                  <span className="hidden sm:block">
                    {address ? shortenAddress(address) : ''}
                  </span>
                </div>
              )}
        </button>

        {/* Disconnect Button (only shown when connected) */}
        {isConnected && (
          <button
            type="button"
            className="btn btn-outline btn-sm font-mono"
            onClick={handleDisconnect}
          >
            <span className="icon-[mdi--logout] w-4 h-4" />
          </button>
        )}
      </div>

      {/* Modal */}
      <dialog ref={connectModalRef} className="modal modal-bottom sm:modal-middle">
        <div className="modal-box max-w-md">
          {/* Header */}
          <div className="flex items-center justify-between mb-6">
            <div>
              <h2 className="text-lg font-medium text-black uppercase tracking-wider">
                CONNECT WALLET
              </h2>
              <p className="text-xs text-gray-500 mt-1">
                Network:
                {' '}
                {connectedChain.name}
              </p>
            </div>
            <button type="button" className="btn btn-sm btn-circle btn-ghost" onClick={closeConnectModal}>
              <span className="icon-[mdi--close] w-4 h-4" />
            </button>
          </div>

          {/* Available Connectors */}
          {filteredConnectors.length > 0
            ? (
                <div className="mb-6">
                  <h3 className="text-xs text-gray-500 uppercase tracking-wider mb-3">
                    Available Wallets
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    {filteredConnectors.map(conn => (
                      <div
                        key={conn.id}
                        className="card card-compact bg-base-100 border border-base-300 hover:border-primary hover:shadow-md transition-all cursor-pointer"
                        onClick={() => handleConnect(conn)}
                      >
                        <div className="card-body items-center text-center">
                          <div className="flex items-center justify-center w-12 h-12 mb-2">
                            {conn.icon
                              ? (
                                  <img
                                    src={conn.icon}
                                    alt={conn.name}
                                    className="w-8 h-8"
                                  />
                                )
                              : (
                                  <span className="icon-[mdi--wallet-outline] w-8 h-8" />
                                )}
                          </div>
                          <div className="text-sm font-medium text-black">
                            {conn.name}
                          </div>
                          <button
                            type="button"
                            disabled={status === 'pending'}
                            className="btn btn-neutral btn-sm w-32 uppercase tracking-wider mt-2"
                          >
                            {status === 'pending'
                              ? (
                                  <>
                                    <span className="icon-[mdi--loading] animate-spin" />
                                    <span>Connecting</span>
                                  </>
                                )
                              : (
                                  <>
                                    <span>Connect</span>
                                    <span className="icon-[mdi--chevron-right]" />
                                  </>
                                )}
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )
            : (
          /* No Connectors Available - Show Popular Wallets */
                <div className="space-y-3">
                  <div className="text-center mb-4">
                    <div className="icon-[mdi--wallet-outline] w-16 h-16 mx-auto text-gray-300 mb-2" />
                    <p className="text-sm text-gray-500">
                      No wallet extensions detected
                    </p>
                    <p className="text-xs text-gray-400">
                      Download a wallet to get started
                    </p>
                  </div>

                  <h3 className="text-xs text-gray-500 uppercase tracking-wider mb-3">
                    Popular Wallets
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    {popularWallets.map(wallet => (
                      <div
                        key={wallet.id}
                        className="card card-compact bg-base-100 border border-base-300 hover:border-primary hover:shadow-md transition-all"
                      >
                        <div className="card-body items-center text-center">
                          <div className="text-sm font-medium text-black mb-3">
                            {wallet.name}
                          </div>
                          <a
                            href={wallet.downloadUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="btn btn-neutral btn-sm w-32 uppercase tracking-wider"
                          >
                            <span>Download</span>
                            <span className="icon-[mdi--download] w-4 h-4" />
                          </a>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

          {/* Error Display */}
          {error && (
            <div className="alert alert-error mt-4">
              <span>{error.message}</span>
            </div>
          )}
        </div>
        <form method="dialog" className="modal-backdrop">
          <button type="button">close</button>
        </form>
      </dialog>
    </>
  )
}
