// templates/ink-v6/dapp-vue-dedot/src/components/Balance.vue
<script setup lang="ts">
import type { Prefix } from '~/utils/sdk'
import { useBalance } from '~/composables/useBalance'

const props = defineProps<{
  address?: string
  chainKey: Prefix
}>()

const { balance, symbol } = useBalance(props.chainKey, props.address)
</script>

<template>
  <div>
    <div class="text-xs text-gray-500 uppercase tracking-wider mb-1">
      Balance
    </div>
    <div class="flex items-baseline space-x-2 font-mono">
      <div class="font-light text-black text-2xl">
        {{ balance || '---' }}
      </div>
      <div class="text-xs text-gray-500 uppercase tracking-wider">
        {{ symbol }}
      </div>
    </div>
  </div>
</template>

// templates/ink-v6/react-dedot/src/components/Balance.tsx
import type { Prefix } from '../utils/sdk'
import { useBalance } from '~/hooks/useBalance'

interface BalanceProps {
  address?: string
  chainKey: Prefix
}

export default function Balance({ address, chainKey }: BalanceProps) {
  const { balance, symbol } = useBalance(chainKey, address)

  return (
    <div>
      <div className="text-xs text-gray-500 uppercase tracking-wider mb-1">
        Balance
      </div>
      <div className="flex items-baseline space-x-2 font-mono">
        <div className="font-light text-black text-2xl">
          {balance || '---'}
        </div>
        <div className="text-xs text-gray-500 uppercase tracking-wider">
          {symbol}
        </div>
      </div>
    </div>
  )
}
