// cli/templates/vue-dedot/src/App.vue
<script setup lang="ts">
import Footer from './components/Footer.vue'
import Header from './components/Header.vue'
import StatusBar from './components/StatusBar.vue'
import TokenCollection from './components/TokenCollection.vue'
</script>

<template>
  <div class="min-h-screen bg-gray-100 pb-12">
    <Header />

    <!-- Main Content -->
    <main>
      <TokenCollection />
    </main>

    <Footer />

    <!-- Sticky Status Bar -->
    <StatusBar />
  </div>
</template>

// cli/templates/react-papi/src/App.tsx
import Footer from './components/Footer'
import Header from './components/Header'
import StatusBar from './components/StatusBar'
import TokenCollection from './components/TokenCollection'

function App() {
  return (
    <div className="min-h-screen bg-gray-100">
      <Header />

      {/* Main Content */}
      <main>
        <TokenCollection />
      </main>

      <Footer />
      <StatusBar />
    </div>
  )
}

export default App
